services:
  - type: web
    name: turkey-carbon-emission-analysis
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn src.web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    staticPublishPath: ./static
    routes:
      - type: rewrite
        source: /static/*
        destination: /static/*
